apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: sampleapp
  name: sampleapp
spec:
  replicas: 3
  selector:
    matchLabels:
      run: sampleapp
  template:
    metadata:
      labels:
        run: sampleapp
    spec:
      containers:
      - image: kissyyy/sampleapp:latest
        name: sampleapp
